package:
  name: aurorafusion
  version: "{{ load_setup_py_data().version }}"

source:
  git_url: git@github.com:fsciortino/aurora.git

build:
  number: 1

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - scipy
    - matplotlib
    - pexpect
    - omfit_classes
    - requests

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - pexpect
    - omfit_classes
    - requests
    
test:
  imports:
    - aurora


about:
  home: https://github.com/fsciortino/aurora	
  license_file: USER_AGREEMENT.txt
  summary: 'Modern toolbox for impurity transport, neutrals and radiation modeling in fusion plasmas'
  description: |
    Aurora is a package to simulate heavy-ion transport, neutrals and radiation in magnetically-confined plasmas. 
    It offers a 1.5D impurity transport forward model inheriting from the historical STRAHL code, 
    with which it has been thoroughly benchmarked. Routines to analyze neutral states of hydrogen 
    isotopes, both from the edge of fusion plasmas and from neutral beam injection, allow integration 
    of impurity and neutral transport analysis.
    Aurora’s code is mostly written in Python 3, with fast low-level components om Fortran90 and Julia.
    The package enables radiation calculations using ADAS atomic rates, which can easily be applied
    to the output of Aurora’s own forward model, or coupled with other 1D, 2D or 3D transport codes.
  doc_url: https://aurora-fusion.readthedocs.io/
  dev_url: https://github.com/fsciortino/aurora


extra:
  recipe-maintainers:
    - fsciortino
